### ISSUE TITLE
NPE: Unsafe access of nullable value

### ISSUE THREAD

**Issue by mantono** [zensum/franz#24]
[Value that can be null](https://github.com/zensum/franz/blob/151db337640268cbbfed152ed388ab8b5bd14ec7/src/main/kotlin/JobState.kt#L161) is accessed in an unsafe manner. This results in a NullPointerException

>subscription-event_1            | 08:02:30.840 [ForkJoinPool.commonPool-worker-1] ERROR f.e.kafka_one.KafkaConsumerActor - Job threw an exception
subscription-event_1            | franz.JobStateException: Listify events
subscription-event_1            |       at franz.JobState$processMap$lastInterceptor$1.doResume(JobState.kt:156)
subscription-event_1            |       at franz.JobState$processMap$lastInterceptor$1.invoke(JobState.kt)
subscription-event_1            |       at franz.JobState$processMap$lastInterceptor$1.invoke(JobState.kt:22)
subscription-event_1            |       at franz.WorkerInterceptor.executeNext(WorkerInterceptor.kt:12)
subscription-event_1            |       at se.zensum.franzSentry.SentryInterceptor$1.doResume(SentryInterceptor.kt:21)
subscription-event_1            |       at se.zensum.franzSentry.SentryInterceptor$1.invoke(SentryInterceptor.kt)
subscription-event_1            |       at se.zensum.franzSentry.SentryInterceptor$1.invoke(SentryInterceptor.kt:16)
subscription-event_1            |       at franz.JobState.processToStatus(JobState.kt:239)
subscription-event_1            |       at franz.JobState.processMap(JobState.kt:160)
subscription-event_1            |       at franz.JobState.mapRequire(JobState.kt:113)
subscription-event_1            |       at se.zensum.subscription_event.SubscriptionEventWorker$getWorkerBuilderEventsIn$2.doResume(SubscriptionEventWorker.kt:55)
subscription-event_1            |       at se.zensum.subscription_event.SubscriptionEventWorker$getWorkerBuilderEventsIn$2.invoke(SubscriptionEventWorker.kt)
subscription-event_1            |       at se.zensum.subscription_event.SubscriptionEventWorker$getWorkerBuilderEventsIn$2.invoke(SubscriptionEventWorker.kt:34)
subscription-event_1            |       at franz.WorkerBuilderKt$pipedWorker$2.doResume(WorkerBuilder.kt:19)
subscription-event_1            |       at franz.WorkerBuilderKt$pipedWorker$2.invoke(WorkerBuilder.kt)
subscription-event_1            |       at franz.WorkerBuilderKt$pipedWorker$2.invoke(WorkerBuilder.kt)
subscription-event_1            |       at franz.engine.kafka_one.KafkaConsumerActor$worker$1$1.doResume(KafkaConsumerActor.kt:170)
subscription-event_1            |       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
subscription-event_1            |       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
subscription-event_1            |       at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
subscription-event_1            |       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
subscription-event_1            |       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
subscription-event_1            |       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
subscription-event_1            |       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
subscription-event_1            |       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
subscription-event_1            | Caused by: kotlin.KotlinNullPointerException: null
subscription-event_1            |       at franz.JobState$processMap$lastInterceptor$1.doResume(JobState.kt:150)
subscription-event_1            |       ... 24 common frames omitted

The stacktrace above references JobState:150, but thats because its an older version, the equivalent for current version in line 161 in JobState.

**Comment by mantono** [comment]
This exception is actually caught and and then rethrown as a JobStateException, which in turn is caught by Franz, which is as it should be.
