### ISSUE TITLE
Franz gets stuck in loop when retrying transient failure with null value

### ISSUE THREAD

**Issue by mantono** [zensum/franz#27]
>kotlin.KotlinNullPointerException: null
    at franz.engine.kafka_one.JobStatusesKt.getOrFail(JobStatuses.kt:8)
    at franz.engine.kafka_one.JobStatusesKt.access$getOrFail(JobStatuses.kt:1)
    at franz.engine.kafka_one.JobStatuses.rescheduleTransientFailures(JobStatuses.kt:46)
    at franz.engine.kafka_one.KafkaConsumerActorKt.retryTransientFailures(KafkaConsumerActor.kt:58)
    at franz.engine.kafka_one.KafkaConsumerActorKt.access$retryTransientFailures(KafkaConsumerActor.kt:1)
    at franz.engine.kafka_one.KafkaConsumerActorKt$consumerLoop$1.invoke(KafkaConsumerActor.kt:123)
    at franz.engine.kafka_one.KafkaConsumerActorKt$consumerLoop$1.invoke(KafkaConsumerActor.kt)
    at franz.engine.kafka_one.KafkaConsumerActorKt.iterate(KafkaConsumerActor.kt:109)
    at franz.engine.kafka_one.KafkaConsumerActorKt.consumerLoop(KafkaConsumerActor.kt:115)
    at franz.engine.kafka_one.KafkaConsumerActorKt.access$consumerLoop(KafkaConsumerActor.kt:1)
    at franz.engine.kafka_one.KafkaConsumerActor$createThread$1.run(KafkaConsumerActor.kt:138)
    at java.lang.Thread.run(Thread.java:748)

This has happened in several different services today. We are investigating the root cause.

**Comment by mantono** [comment]
Fixed in #28
