### ISSUE TITLE
Exception: Error reading array of size 9092, only 916 bytes available

### ISSUE THREAD

**Issue by mantono** [zensum/franz#9]
> Exception in thread "Thread-2" org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'responses': Error reading field 'partition_responses': Error reading array of size 9092, only 916 bytes available
>     at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:75)
>     at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:153)
>     at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:559)
>     at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:655)
>     at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:441)
>     at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:232)
>     at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:208)
>     at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1096)
>     at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
>     at franz.internal.ConsumerActorKt.fetchMessagesFromKafka(ConsumerActor.kt:39)
>     at franz.internal.ConsumerActorKt.access$fetchMessagesFromKafka(ConsumerActor.kt:1)
>     at franz.internal.ConsumerActorKt$consumerLoop$1.invoke(ConsumerActor.kt:107)
>     at franz.internal.ConsumerActorKt$consumerLoop$1.invoke(ConsumerActor.kt)
>     at franz.internal.ConsumerActorKt.iterate(ConsumerActor.kt:98)
>     at franz.internal.ConsumerActorKt.consumerLoop(ConsumerActor.kt:104)
>     at franz.internal.ConsumerActorKt.access$consumerLoop(ConsumerActor.kt:1)
>     at franz.internal.ConsumerActor$createThread$1.run(ConsumerActor.kt:126)
>     at java.lang.Thread.run(Thread.java:748)

@williamhogman Any ideas?

**Comment by mantono** [comment]
Same problem in project sms-to-mail-notifications. Since updating to latest version of Franz seemed to solve the problem, I will try that here as well.

**Comment by mantono** [comment]
Problem cannot be reproduced when all server/clients are running same version (0.11.0). Will assume it was because of a version mismatch problem.
